---
- name: ensure vaultwarden directories exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ vaultwarden_cert_path }}'
    - '{{ vaultwarden_data_path }}'
    - '{{ vaultwarden_db_path }}'
    - /var/www/letsencrypt

- include_tasks:
    file: nginx.yml
- name: setup vaultwarden via podman
  include_tasks: vaultwarden.yml
- include_tasks: systemd.yml
