---
- name: ensure podman is installed
  package:
    name:
      - podman
      - containernetworking-plugins
      - fuse-overlayfs
    state: latest
    update_cache: yes
    cache_valid_time: 3600
