---
- name: ensure vaultwarden.service exists
  template:
    src: "vaultwarden.service.j2"
    dest: "/etc/systemd/system/{{ vaultwarden_name }}.service"
    mode: 0644

- name: ensure vaultwarden.service is enabled and started
  systemd:
    name: "{{ vaultwarden_name }}.service"
    state: started
    scope: system
    enabled: yes
