---
- name: start nginx
  systemd:
    name: "nginx.service"
    state: started

- name: restart nginx
  systemd:
    name: "nginx.service"
    state: restarted

- name: reload nginx
  systemd:
    name: "nginx.service"
    state: reloaded

- name: restart vaultwarden
  systemd:
    name: "{{ vaultwarden_name }}.service"
    state: restarted
